spring:
  datasource:
     url: jdbc:mysql://localhost:3306/oasis3?serverTimezone=CTT&characterEncoding=UTF-8&useAffectedRows=true
     username: root
     password: Huang2748368181
#  Huang2748368181
     driver-class-name: com.mysql.cj.jdbc.Driver
     max-active: 200
     max-idle: 20
     min-idle: 10
  thymeleaf:
     cache: false
     prefix: classpath:/templates/
  jackson:
    time-zone: GMT+8
  resources:
    static-locations:classpath:static/
server:
  port: 8020
mybatis:
  mapper-locations: classpath:datamapper/*mapper.xml

